services:
  # Base de datos
  database:
    image: postgres:15-alpine
    container_name: SafeTrack-DB
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safetrack_network

  # Interfaz visual para DB
  pgadmin:
    image: dpage/pgadmin4
    container_name: SafeTrack-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-password}
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - safetrack_network

  # Redis para caché y colas
  redis:
    image: 'redis:alpine'
    container_name: SafeTrack-Redis
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'safetrack_redis:/data'
    networks:
      - safetrack_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  # Servidor de correo para pruebas
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: SafeTrack-mail
    ports:
        - '1025:1025'
        - '8025:8025'
    networks:
        - safetrack_network

networks:
  safetrack_network:
    driver: bridge

volumes:
  postgres_data:
  safetrack_redis:
    driver: local
